Hometasks/hometask03
Frtn0717/add pull request #1
Opened 2021-08-04 12:27 UTC by Frtn0717

2021-08-11 08:09 UTC, ArtsiomFinenka requested changes

2021-08-11 08:09 UTC, ArtsiomFinenka commented on hometask03/add.js
> +    console.log(result);
Why do we need the second if in this statement? If you deleted this part, the last else will handle the single object

2021-08-11 08:09 UTC, ArtsiomFinenka commented on hometask03/add.js
> +    throw new Error('Needs at least 1 argument');
instead of throwing an error let's return `null`

2021-08-11 08:09 UTC, ArtsiomFinenka commented on hometask03/add.js
> +    }
If you change this part using "reduce" method instead of for() then it will be pretty cool

2021-08-11 08:09 UTC, ArtsiomFinenka commented on hometask03/add.js
> +function findIntersect() {
The same comments like in add() function

2021-08-11 08:09 UTC, ArtsiomFinenka commented on hometask03/add.js
> +function findIntersectInArr() {
The same comments like in add() function

2021-08-12 07:04 UTC, ArtsiomFinenka requested changes

2021-08-18 07:06 UTC, ArtsiomFinenka approved these changes

2021-08-18 07:06 UTC, ArtsiomFinenka commented on hometask03/add.js
> +    }, Object.assign({}, args.shift(0)));
`args.shift(0)` ???
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/shift

2021-08-18 15:36 UTC, Frtn0717 commented on hometask03/add.js
> +    }, Object.assign({}, args.shift(0)));
My bad

2021-08-18 15:39 UTC, merged